//Types for Login
export const LOGIN_REQUEST_REQUEST = 'LOGIN_REQUEST_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';

//Types for Save User Info
export const SAVE_INFO_REQUEST = 'SAVE_INFO_REQUEST';
export const SAVE_INFO_SUCCESS = 'SAVE_INFO_SUCCESS';
export const SAVE_INFO_FAILURE = 'SAVE_INFO_FAILURE';

//Types for OTP Verification
export const OTP_VERIFY_REQUEST = 'OTP_VERIFY_REQUEST';
export const OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS';
export const OTP_VERIFY_FAILURE = 'OTP_VERIFY_FAILURE';

//Types for  Resend OTP

export const RESEND_OTP_REQUEST = 'RESEND_OTP_REQUEST';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_FAILURE = 'RESEND_OTP_FAILURE';

//Types for  forgot password
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

//Types for Update Password
export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE';

//Types for reset password
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

//Types for Logout
export const LOGOUT_REQUEST_REQUEST = 'LOGOUT_REQUEST_REQUEST';
export const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS';
export const LOGOUT_REQUEST_FAILURE = 'LOGOUT_REQUEST_FAILURE';

//Types for Update profile

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

export const SAVE_SIGNUP_OBJECT = 'SAVE_SIGNUP_OBJECT';

export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE';

export const GET_USER_POINTS_REQUEST = 'GET_USER_POINTS_REQUEST';
export const GET_USER_POINTS_SUCCESS = 'GET_USER_POINTS_SUCCESS';
export const GET_USER_POINTS_FAILURE = 'GET_USER_POINTS_FAILURE';

export const UPDATE_FCM_TOKEN_REQUEST = 'UPDATE_FCM_TOKEN_REQUEST';
export const UPDATE_FCM_TOKEN_SUCCESS = 'UPDATE_FCM_TOKEN_SUCCESS';
export const UPDATE_FCM_TOKEN_FAILURE = 'UPDATE_FCM_TOKEN_FAILURE';

export const DESTROY_FCM_TOKEN_REQUEST = 'DESTROY_FCM_TOKEN_REQUEST';
export const DESTROY_FCM_TOKEN_SUCCESS = 'DESTROY_FCM_TOKEN_SUCCESS';
export const DESTROY_FCM_TOKEN_FAILURE = 'DESTROY_FCM_TOKEN_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const USER_SUPPORT_REQUEST = 'USER_SUPPORT_REQUEST';
export const USER_SUPPORT_SUCCESS = 'USER_SUPPORT_SUCCESS';
export const USER_SUPPORT_FAILURE = 'USER_SUPPORT_FAILURE';

export const VERIFY_KEY_REQUEST = 'VERIFY_KEY_REQUEST';
export const VERIFY_KEY_SUCCESS = 'VERIFY_KEY_SUCCESS';
export const VERIFY_KEY_FAILURE = 'VERIFY_KEY_FAILURE';
export const INVITE_URL = 'INVITE_URL';

export const GET_EMAIL_REQUEST = 'GET_EMAIL_REQUEST';
export const GET_EMAIL_SUCCESS = 'GET_EMAIL_SUCCESS';
export const GET_EMAIL_FAILURE = 'GET_EMAIL_FAILURE';
