export const GET_LEADERBOARD_USERS_REQUEST = 'GET_LEADERBOARD_USERS_REQUEST';
export const GET_LEADERBOARD_USERS_SUCCESS = 'GET_LEADERBOARD_USERS_SUCCESS';
export const GET_LEADERBOARD_USERS_FAILURE = 'GET_LEADERBOARD_USERS_FAILURE';

export const GET_LEADERBOARD_USER_DETAILS_REQUEST =
  'GET_LEADERBOARD_USER_DETAILS_REQUEST';
export const GET_LEADERBOARD_USER_DETAILS_SUCCESS =
  'GET_LEADERBOARD_USER_DETAILS_SUCCESS';
export const GET_LEADERBOARD_USER_DETAILS_FAILURE =
  'GET_LEADERBOARD_USER_DETAILS_FAILURE';

export const CHALLENGE_USER_REQUEST = 'CHALLENGE_USER_REQUEST';
export const CHALLENGE_USER_SUCCESS = 'CHALLENGE_USER_SUCCESS';
export const CHALLENGE_USER_FAILURE = 'CHALLENGE_USER_FAILURE';
