export const SELECTED_LEGACY_STATEMENT = 'SELECTED_LEGACY_STATEMENT';
export const VIEW_SELECTED_LEGACY_STATEMENT = 'VIEW_SELECTED_LEGACY_STATEMENT';

export const GET_DAILY_MOTIVATION_REQUEST = 'GET_DAILY_MOTIVATION_REQUEST';
export const GET_DAILY_MOTIVATION_SUCCESS = 'GET_DAILY_MOTIVATION_SUCCESS';
export const GET_DAILY_MOTIVATION_FAILURE = 'GET_DAILY_MOTIVATION_FAILURE';

export const CREATE_DAILY_MOTIVATION_REQUEST =
  'CREATE_DAILY_MOTIVATION_REQUEST';
export const CREATE_DAILY_MOTIVATION_SUCCESS =
  'CREATE_DAILY_MOTIVATION_SUCCESS';
export const CREATE_DAILY_MOTIVATION_FAILURE =
  'CREATE_DAILY_MOTIVATION_FAILURE';

export const UPDATE_LEGACY_REQUEST = 'UPDATE_LEGACY_REQUEST';
export const UPDATE_LEGACY_SUCCESS = 'UPDATE_LEGACY_SUCCESS';
export const UPDATE_LEGACY_FAILURE = 'UPDATE_LEGACY_FAILURE';

export const DELETE_LEGACY_REQUEST = 'DELETE_LEGACY_REQUEST';
export const DELETE_LEGACY_SUCCESS = 'DELETE_LEGACY_SUCCESS';
export const DELETE_LEGACY_FAILURE = 'DELETE_LEGACY_FAILURE';
