export const CHANGE_CHALLENGE_STATUS = 'CHANGE_CHALLENGE_STATUS';
export const ALL_TASKS_COMPLETED = 'ALL_TASKS_COMPLETED';
export const WON_DAY = 'WON_DAY';
export const SHOW_LEGACY_STATEMENT = 'SHOW_LEGACY_STATEMENT';

export const GET_CHAMPIONSHIP_TASK_REQUEST = 'GET_CHAMPIONSHIP_TASK_REQUEST';
export const GET_CHAMPIONSHIP_TASK_SUCCESS = 'GET_CHAMPIONSHIP_TASK_SUCCESS';
export const GET_CHAMPIONSHIP_TASK_FAILURE = 'GET_CHAMPIONSHIP_TASK_FAILURE';

export const COMPLETE_CHAMPIONSHIP_TASK_REQUEST =
  'COMPLETE_CHAMPIONSHIP_TASK_REQUEST';
export const COMPLETE_CHAMPIONSHIP_TASK_SUCCESS =
  'COMPLETE_CHAMPIONSHIP_TASK_SUCCESS';
export const COMPLETE_CHAMPIONSHIP_TASK_FAILURE =
  'COMPLETE_CHAMPIONSHIP_TASK_FAILURE';

export const GET_ACTION_ITEM_REQUEST = 'GET_ACTION_ITEM_REQUEST';
export const GET_ACTION_ITEM_SUCCESS = 'GET_ACTION_ITEM_SUCCESS';
export const GET_ACTION_ITEM_FAILURE = 'GET_ACTION_ITEM_FAILURE';

export const COMPLETE_ACTION_ITEM_REQUEST = 'COMPLETE_ACTION_ITEM_REQUEST';
export const COMPLETE_ACTION_ITEM_SUCCESS = 'COMPLETE_ACTION_ITEM_SUCCESS';
export const COMPLETE_ACTION_ITEM_FAILURE = 'COMPLETE_ACTION_ITEM_FAILURE';

export const GET_ACTIVE_CHALLENGE_REQUEST = 'GET_ACTIVE_CHALLENGE_REQUEST';
export const GET_ACTIVE_CHALLENGE_SUCCESS = 'GET_ACTIVE_CHALLENGE_SUCCESS';
export const GET_ACTIVE_CHALLENGE_FAILURE = 'GET_ACTIVE_CHALLENGE_FAILURE';

export const GET_INACTIVE_CHALLENGE_REQUEST = 'GET_INACTIVE_CHALLENGE_REQUEST';
export const GET_INACTIVE_CHALLENGE_SUCCESS = 'GET_INACTIVE_CHALLENGE_SUCCESS';
export const GET_INACTIVE_CHALLENGE_FAILURE = 'GET_INACTIVE_CHALLENGE_FAILURE';

export const KICK_ASS_REQUEST = 'KICK_ASS_REQUEST';
export const KICK_ASS_SUCCESS = 'KICK_ASS_SUCCESS';
export const KICK_ASS_FAILURE = 'KICK_ASS_FAILURE';

export const ACCEPT_CHALLENGE_REQUEST = 'ACCEPT_CHALLENGE_REQUEST';
export const ACCEPT_CHALLENGE_SUCCESS = 'ACCEPT_CHALLENGE_SUCCESS';
export const ACCEPT_CHALLENGE_FAILURE = 'ACCEPT_CHALLENGE_FAILURE';

export const REJECT_CHALLENGE_REQUEST = 'REJECT_CHALLENGE_REQUEST';
export const REJECT_CHALLENGE_SUCCESS = 'REJECT_CHALLENGE_SUCCESS';
export const REJECT_CHALLENGE_FAILURE = 'REJECT_CHALLENGE_FAILURE';

export const GET_STREAKS_RECORD_REQUEST = 'GET_STREAKS_RECORD_REQUEST';
export const GET_STREAKS_RECORD_SUCCESS = 'GET_STREAKS_RECORD_SUCCESS';
export const GET_STREAKS_RECORD_FAILURE = 'GET_STREAKS_RECORD_FAILURE';

export const DELETE_ACTION_ITEMS_REQUEST = 'DELETE_ACTION_ITEMS_REQUEST';
export const DELETE_ACTION_ITEMS_SUCCESS = 'DELETE_ACTION_ITEMS_SUCCESS';
export const DELETE_ACTION_ITEMS_FAILURE = 'DELETE_ACTION_ITEMS_FAILURE';

export const DELETE_CHAMPIONSHIP_TASK_REQUEST = 'DELETE_CHAMPIONSHIP_TASK_REQUEST';
export const DELETE_CHAMPIONSHIP_TASK_SUCCESS = 'DELETE_CHAMPIONSHIP_TASK_SUCCESS';
export const DELETE_CHAMPIONSHIP_TASK_FAILURE = 'DELETE_CHAMPIONSHIP_TASK_FAILURE';
