export const CLEAR_ONBOARDING = 'CLEAR_ONBOARDING';

export const CREATE_CLIENT_ONBOARDING_REQUEST =
  'CREATE_CLIENT_ONBOARDING_REQUEST';
export const CREATE_CLIENT_ONBOARDING_SUCCESS =
  'CREATE_CLIENT_ONBOARDING_SUCCESS';
export const CREATE_CLIENT_ONBOARDING_FAILURE =
  'CREATE_CLIENT_ONBOARDING_FAILURE';

export const GET_CLIENT_ONBOARDING_REQUEST = 'GET_CLIENT_ONBOARDING_REQUEST';
export const GET_CLIENT_ONBOARDING_SUCCESS = 'GET_CLIENT_ONBOARDING_SUCCESS';
export const GET_CLIENT_ONBOARDING_FAILURE = 'GET_CLIENT_ONBOARDING_FAILURE';

export const SAVE_ONBOARDING_QUESTION_ANSWER =
  'SAVE_ONBOARDING_QUESTION_ANSWER';

export const GET_ONBOARDING_FORM_REQUEST = 'GET_ONBOARDING_FORM_REQUEST';
export const GET_ONBOARDING_FORM_SUCCESS = 'GET_ONBOARDING_FORM_SUCCESS';
export const GET_ONBOARDING_FORM_FAILURE = 'GET_ONBOARDING_FORM_FAILURE';
