export const CREATE_CHAMPIONSHIP_TASK_REQUEST =
	'CREATE_CHAMPIONSHIP_TASK_REQUEST';
export const CREATE_CHAMPIONSHIP_TASK_SUCCESS =
	'CREATE_CHAMPIONSHIP_TASK_SUCCESS';
export const CREATE_CHAMPIONSHIP_TASK_FAILURE =
	'CREATE_CHAMPIONSHIP_TASK_FAILURE';

export const CREATE_ACTION_ITEM_REQUEST = 'CREATE_ACTION_ITEM_REQUEST';
export const CREATE_ACTION_ITEM_SUCCESS = 'CREATE_ACTION_ITEM_SUCCESS';
export const CREATE_ACTION_ITEM_FAILURE = 'CREATE_ACTION_ITEM_FAILURE';

export const CREATE_NOTE_TO_COACH_REQUEST = 'CREATE_NOTE_TO_COACH_REQUEST';
export const CREATE_NOTE_TO_COACH_SUCCESS = 'CREATE_NOTE_TO_COACH_SUCCESS';
export const CREATE_NOTE_TO_COACH_FAILURE = 'CREATE_NOTE_TO_COACH_FAILURE';

export const GET_NOTES_REQUEST = 'GET_NOTES_REQUEST';
export const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS';
export const GET_NOTES_FAILURE = 'GET_NOTES_FAILURE';

export const NOTES_BY_COACH_REQUEST = 'NOTES_BY_COACH_REQUEST';
export const NOTES_BY_COACH_SUCCESS = 'NOTES_BY_COACH_SUCCESS';
export const NOTES_BY_COACH_FAILURE = 'NOTES_BY_COACH_FAILURE';
